version: "3.8"
services:

  mysqldb:
    platform: linux/arm64
    image: mysql:8.4.0
    restart: unless-stopped
    env_file: ./.env
    ports:
      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLDB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQLDB_DATABASE}
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -uroot -p${MYSQLDB_ROOT_PASSWORD} || exit 1" ]
      interval: 30s
      timeout: 30s
      retries: 5
  app:
    build: .
    image: task-management-app
    depends_on:
      mysqldb:
        condition: service_healthy
    restart: no
    env_file: ./.env
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
      - ${DEBUG_PORT}:${DEBUG_PORT}
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE
      - SPRING_DATASOURCE_USERNAME=$MYSQLDB_USER
      - SPRING_DATASOURCE_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - SPRING_MAIL_HOST=${SPRING_MAIL_HOST}
      - SPRING_MAIL_PORT=${SPRING_MAIL_PORT}
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=false
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=false
  mailhog:
    image: mailhog/mailhog
    restart: unless-stopped
    env_file: ./.env
    ports:
      - ${SPRING_MAIL_PORT}:${SPRING_MAIL_PORT}
      - "8025:8025"